feat(docker): add CI steps and Dockerfile
tf2pickup-org/docs.tf2pickup.org pull request #43
Opened 2023-04-15 10:12 UTC by suprovsky

2023-04-15 11:18 UTC, garrappachc requested changes

2023-04-15 11:18 UTC, garrappachc commented on .github/workflows/build-docker-image.yml
> +  IMAGE_NAME: "etf2l/${{ github.event.repository.name }}"
Why the `etf2l` prefix?

2023-04-15 11:18 UTC, garrappachc commented on Dockerfile
> +FROM node:18 AS build
Use `node:lts-alpine` image

2023-04-15 11:18 UTC, garrappachc commented on Dockerfile
> +      org.opencontainers.image.base.name="ghcr.io/tf2pickup-org/:1.0.0" \
Fix image name

2023-04-15 11:23 UTC, garrappachc commented
Also, scope of this PR should be **build**: `feat(build): add CI scripts and Dockerfile`

2023-04-15 23:26 UTC, suprovsky commented on .github/workflows/build-docker-image.yml
> +  IMAGE_NAME: "etf2l/${{ github.event.repository.name }}"
my bad :D

2023-04-16 19:53 UTC, garrappachc approved these changes

2023-04-16 22:03 UTC, merged